# Generated by Django 3.2.13 on 2022-06-01 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0002_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Siting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siting.breed')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
