# Generated by Django 3.2.13 on 2022-06-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0003_auto_20220601_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siting',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='siting',
            unique_together={('breed_id', 'date')},
        ),
    ]
