# Generated by Django 3.2.13 on 2022-06-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siting', '0005_alter_siting_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siting',
            unique_together={('breed_id', 'date')},
        ),
    ]
